### ISSUE TITLE
Problem parsing docx files

### ISSUE THREAD

**Issue by rbhavnani** [JBGruber/LexisNexisTools#11]
Hello, 

Thanks, Johannes, for this wonderful public good.  Quick question: I am trying to parse a series of DOCX files that I downloaded from Nexis Uni. Several of these files give the following error:

"More than one language was detected. Choose one: 

1: Don't convert dates
2: English (97.87%)
3: NA (NA%)"

When I choose 2, the program is able to extract 40 articles from the attached file, even though there are 100 articles.  Help, please?

Thanks.
Rik

[Files(100) (10).DOCX](https://github.com/JBGruber/LexisNexisTools/files/3745213/Files.100.10.DOCX)

**Comment by JBGruber** [comment]
Thanks for reporting the issue. The problem was that you had two consecutive empty lines in the middle of an article. Usually two empty lines indicate the end of the cover page --- which is removed. I found a better way to remove the cover page, so it should work now. Let me know if there are further issues.

**Comment by rbhavnani** [comment]
Thanks much for the quick fix, Johannes!  This is super helpful.

Rikhil

**Comment by JBGruber** [comment]
Great! I assume this means the issue can be closed.
