### ISSUE TITLE
Ideas for lnt_rename

### ISSUE THREAD

**Issue by dsschiff** [JBGruber/LexisNexisTools#15]
Enjoying the package a lot.

It seems quite difficult to get the cover pages to download correctly or with full information, even using the manual select or working through a link as you suggest. I'm not sure if cover pages are simply not provided for different years, sources, etc.

Also, since I'm using the same search term and many articles come from the same range, the current naming scheme also isn't as helpful as it could be.

I wonder if there is an alternative naming scheme that could be implanted. For example, my articles at least seem to give a date. Perhaps articles can be renamed with something like ID_[snake_case of title]_DDMMYYYY. ID could come from your other parsing code, which seems to work nicely.

I'm sure you have better version of these ideas; just wanted to throw out some suggestions for your consideration RE renaming.

Thanks!

**Comment by JBGruber** [comment]
Thanks for the suggestion @dsschiff! I wrote the function for my own convenience mostly and received the feedback that most people don't really care --- so I forgot about it a little since my last project with newspaper data. I'm not even entirely sure at the moment if the function still works with files from the new Lexis Uni interface.

I will try to resurrect it, once my schedule isn't quite as full as now. But in the meantime, I think it would be relatively easy to get this done yourself *after* reading in the files once:

``` r
library(LexisNexisTools)
library(tidyverse)
data <- lnt_read(lnt_sample(format = "docx"), verbose = FALSE)

```

All the information you need is already there in the `meta` `data.frame`. Using some data wrangling, we can get the new file name:

```
rename_df <- data@meta %>%  
  mutate(old_name = basename(Source_File),
         new_name = paste0(ID, "_", 
                           strtrim(Headline, width = 15), "_", # trimming the title a bit
                           format(Date, "%d%b%Y"), ".",
                           tools::file_ext(Source_File)),
         New_File = paste0(dirname(Source_File), new_name)) %>% 
  select(old_name, new_name, Source_File, New_File)
```

Now you can look at just the `old_name` and `new_name` to make sure you are happy with the new names:

```
rename_df %>% 
  select(old_name, new_name)
#> # A tibble: 10 x 2
#>    old_name    new_name                         
#>    <chr>       <chr>                            
#>  1 sample.DOCX 1_Lorem ipsum dol_01Jul2019.DOCX 
#>  2 sample.DOCX 2_Lorem ipsum dol_02Jul2019.DOCX 
#>  3 sample.DOCX 3_Lorem ipsum dol_04Jul2019.DOCX 
#>  4 sample.DOCX 4_Lorem ipsum dol_03Jul2019.DOCX 
#>  5 sample.DOCX 5_Lorem ipsum dol_04Jul2019.DOCX 
#>  6 sample.DOCX 6_Lorem ipsum dol_02Jul2019.DOCX 
#>  7 sample.DOCX 7_Sample Headline_03Jul2019.DOCX 
#>  8 sample.DOCX 8_Lorem ipsum dol_03Jul2019.DOCX 
#>  9 sample.DOCX 9_R (programming _03Jul2019.DOCX 
#> 10 sample.DOCX 10_What is Wikiped_02Jul2019.DOCX
```

If you have several articles coming from the same file, you have to remove duplicates first now (otherwise you'll get some errors, which isn't a big deal either).

```
rename_df_clean <- rename_df %>% 
  filter(!duplicated(Source_File))
```

Once ready, you can rename your files super fast just like this:

```
file.rename(from = rename_df_clean$Source_File, to = rename_df_clean$New_File)
```

Hope that helps :)

**Comment by dsschiff** [comment]
This is great - very kind of you to pull this code together. I tested it out after applying the duplication procedures you also provide, and it works nicely. Thanks again!

**Comment by JBGruber** [comment]
It's a nice idea, but I'm not activly adding new functions.
