### ISSUE TITLE
Identifying a few missing articles after running lnt_read() on .docx?

### ISSUE THREAD

**Issue by violawiegand** [JBGruber/LexisNexisTools#21]
This is possibly a user error, rather than an issue. I would be very grateful for any tips.
Lexis Advance doesn't seem to output text files anymore, so we have exported Word files in chunks of 500 articles per file. I was very happy to come across this package and have used the `lnt_read()` function successfully to read in most of the articles. However, from the 500 articles in the first file, it just read in 499. And from the 6 x 500 article Word files I have tried, it recognised 2,994 articles. 

Do you have any tips on how I can find the missing 6? (And are they actually missing, or have they been automatically removed because they are not complete / or duplicates or something like that? I did not run `lnt_similarity()`...)

It's a bit of a pain of navigating such long Word documents (> 1000 pages), but when searching for "End of Document" in the first Word file, I do get 500 results, rather than just 499, so that doesn't seem to be an issue.

It might also be worth stating that there was a warning about (very few) dates in different languages when running `lnt_read()` and I selected the option of converting to English. Not sure if this has caused problems?
Thanks!!

**Comment by violawiegand** [comment]
Ok, I should have checked this before posting, but it looks like it's the first article of each document that isn't recognised. I think this may be because the Word version doesn't seem to include the "Document X out of X" info, but instead just the "End of Document" line which the package may rely on? And since it doesn't occur before the first one, that one is probably missed out? Is there any setting I can change? Or would I need to hack it by adding fake "End of Document" before the first one...?

**Comment by violawiegand** [comment]
another update: the function seems to assume that the Word document has a table of contents. This was not the case for our data. As it's a lot of work to re-download the 30,000 articles/60 files we had downloaded with a cover page, I have tried manually adding a first page with "Documents: 500" followed by a page break. That seems to work. If there is a neater way to do this, I'd be happy to hear about it. Or maybe something can be added to the documentation that a cover page is mandatory for the first article in docx files to be recognised (as they don't necessarily contain "Document X of X"?
(apologies if I missed that somewhere!).

**Comment by JBGruber** [comment]
Did you look at this? https://github.com/JBGruber/LexisNexisTools/issues/14#issuecomment-652507407

I will have a closer look later.

**Comment by violawiegand** [comment]
thank you very much for the quick response! `remove_cover = FALSE` seems to do the trick :) 
I did not realise this was related, as I thought that argument only applies when you do have a cover page. Makes sense, though, thanks!

**Comment by JBGruber** [comment]
Ok, so here is a little bit of background to this: Usually, files from LexisNexis came/come with a cover page. I've been removing this from a very early version on. The current code looks like this:

https://github.com/JBGruber/LexisNexisTools/blob/958928db942e0044adddb93afc0e6bd2010d9eb2/R/LexisNexisTools.R#L630-L644

It's a little obscure, but basically the cover page is followed by two empty lines. If no cover page is present, these lines of code should do nothing.

It looks, however, as if LexisNexis has started to use two empty lines between articles, which is why the first article in a document is identified as the cover page and is removed. I don't have access to Lexis Advance and in the few files that were sent to me, I haven't found an automated way of identifying if the cover page or an article is removed. Hence, the somewhat clunky solution with `remove_cover = FALSE`. I hope I can get something more elegant in the future.

Please close this issue if you have no further questions.
