### ISSUE TITLE
duplicates on different days

### ISSUE THREAD

**Issue by czymara** [JBGruber/LexisNexisTools#3]
Thanks a lot for the great and very helpful package! My issue regards the identification of duplicates: I have data on news articles from the print version of Die Zeit (published weekly) and from the online version of Zeit Online (published daily). While the lion's share of articles are mutually exclusive, some of the print articles are also published online some days after they were published in print. As far as I know, such duplicates on different days are not identified by the lnt_similarity, right? Is there any way to change the time frame or grouping of the comparison?

Best,
Christian

**Comment by JBGruber** [comment]
Thanks for raising this issue and for your interest in the package.

`lnt_similarity()` only checks the articles published on the same date for similarity. This is a deliberate choice since I believe that articles published on different dates should not be treated as duplicates. If someone makes a point why this might not be true in some cases, I could think about implementing a grouping option.

Since in your special case I see the point, you could apply this 'hack' to force `lnt_similarity()` to check the similarity of articles over more than one date:

- You extract the date from the LNToutput object (I call it `test` here) and make all values the same:

```
dates <- test@meta$Date
dates <- rep(dates[1], length(dates))
```
- Then you provide `texts`, `dates` and `IDs` separately, forcing `lnt_similarity()` to treat all articles like they were published on the same date:

```
duplicates.df <- lnt_similarity(texts = test@articles$Article,
                                dates = dates,
                                IDs = test@articles$ID,
                                threshold = 0.95,
                                rel_dist = FALSE)
```
If this solution is too radical, you can also think about grouping the dates together, e.g., by:

- year:
`dates <- as.Date(paste0(format(test@meta$Date, "%Y"), "-01-01"))`
- month:
`dates <- as.Date(paste0(format(test@meta$Date, "%Y"), "%Y-%m"), "-01"))`
- or week:
```
library(dplyr)
library(tibble)
dates <- test@meta$Date %>%
  tibble(day = .,
         week = format(., "%Y-%m:%W")) %>%
  group_by(week) %>%
  mutate(first = min(day))
```
And then provide `texts`, `dates` and `IDs` separately to `lnt_similarity()` again. That should do the trick :grin:
